# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ansicube < Formula
  desc "Interactive ANSI 256-color explorer for the terminal"
  homepage "https://github.com/maxludden/ansiCube"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxludden/ansiCube/releases/download/v0.1.6/ansicube_0.1.6_darwin_amd64.tar.gz"
      sha256 "5b2493a1fc059babf562f867d9a1361d171cfe5afb86192647d3969d01b3eb9f"

      def install
        bin.install "ansicube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxludden/ansiCube/releases/download/v0.1.6/ansicube_0.1.6_darwin_arm64.tar.gz"
      sha256 "df4119e0a4f3b02054d88b810deb1c1149dac05c1db2f5f1fa0611e8bad82ad8"

      def install
        bin.install "ansicube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxludden/ansiCube/releases/download/v0.1.6/ansicube_0.1.6_linux_amd64.tar.gz"
      sha256 "71a94a23fff917a35f2c884a676b1076d40041dc00f983087d071609410bcfb5"
      def install
        bin.install "ansicube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxludden/ansiCube/releases/download/v0.1.6/ansicube_0.1.6_linux_arm64.tar.gz"
      sha256 "d67722c05d1ef5b7e0c2bc89a40b578ffee27f9b6d55bac1b6619f394eca6cb7"
      def install
        bin.install "ansicube"
      end
    end
  end
end
