# This file was generated by GoReleaser. DO NOT EDIT.
cask "ansicube" do
  name "ansicube"
  desc "Interactive ANSI 256-color explorer for the terminal"
  homepage "https://github.com/maxludden/ansiCube"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ansicube"

  on_macos do
    on_intel do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_darwin_amd64.tar.gz"
      sha256 "58fa2163d79abf1caa1d4e6c76874399b4c4d68e9ce9e5ae836cefb19c285092"
    end
    on_arm do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_darwin_arm64.tar.gz"
      sha256 "bac47bbb0f82c9d384ac2adf16ff88d310cfa1c8cfa8b4576905fe3dbe8de463"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_linux_amd64.tar.gz"
      sha256 "1223104ca37cad11ecd78d5e65b8bebca52cdf4c06c9fceb69980849d98950a8"
    end
    on_arm do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_linux_arm64.tar.gz"
      sha256 "0423c6b0c49d13cc8cd25035d914e238763683e51d4f99da3820b88f2a8ad1ca"
    end
  end

  # No zap stanza required
end
