# This file was generated by GoReleaser. DO NOT EDIT.
cask "ansicube" do
  name "ansicube"
  desc "Interactive ANSI 256-color explorer for the terminal"
  homepage "https://github.com/maxludden/ansiCube"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ansicube"

  on_macos do
    on_intel do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_darwin_amd64.tar.gz"
      sha256 "8f9671c2a44dcac649b4962dee3f3d4fe9463679df2c8546f70e50f70e5c9bdf"
    end
    on_arm do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_darwin_arm64.tar.gz"
      sha256 "810128911698ee1818a570ee1548f47798f8f73d2228003f75030031bf19639d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_linux_amd64.tar.gz"
      sha256 "99b4824d86fbfc970b7df23ae3dafe9fde6fc371629038832a2341933ef2bc5c"
    end
    on_arm do
      url "https://github.com/maxludden/ansiCube/releases/download/v#{version}/ansicube_#{version}_linux_arm64.tar.gz"
      sha256 "65203f872b66ecbfcb23a8787bcfcdac48e71072f293874c7e1d319d6832692b"
    end
  end

  # No zap stanza required
end
